# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    environment: main
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install
      - name: npm install
        run: npm install

      # test
      - name: npm test
        id: test
        run: npm test
        continue-on-error: true

      - name: error handle package-lock.json
        if: job.steps.test.status == failure() 
        run: rm -rf package-lock.json node_modules; npm install; npm test

      # coverage
      - name: coverage
        run: npm run coverage

      # codecov
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
